# Generated by Django 3.2.4 on 2021-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toorder',
            name='size',
            field=models.CharField(choices=[('Lg', 'Великий'), ('Md', 'Середній'), ('Sm', 'Маленький')], max_length=10),
        ),
    ]
