# Generated by Django 3.2.4 on 2021-08-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_products_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Фотографія ',
                'verbose_name_plural': 'Фотографії',
            },
        ),
        migrations.CreateModel(
            name='ImagesForSlider',
            fields=[
                ('images_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.images')),
                ('in_slider', models.BooleanField(default=False)),
            ],
            bases=('Products.images',),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('photos', models.ManyToManyField(related_name='collection', to='Products.Images')),
                ('products', models.ManyToManyField(related_name='collection', to='Products.Products')),
            ],
            options={
                'verbose_name': 'Колекція',
                'verbose_name_plural': 'Колекції',
            },
        ),
    ]
