# Generated by Django 3.2.4 on 2021-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_collection_images_imagesforslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=170, null=True, unique=True),
        ),
    ]
