# Generated by Django 3.2.4 on 2021-08-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_collection_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesforslider',
            options={'verbose_name': 'Фотографія для слайдера', 'verbose_name_plural': 'Фотографії для слайдера'},
        ),
    ]
